### ISSUE TITLE
get_dr_txt.py生成的results中没有内容

### ISSUE THREAD

**Issue by indigohana** [bubbliiiing/yolov4-pytorch#139]
大佬好，在计算map的时候生成detection results，但是生成的txt文件里没有内容，然后get_map.py提示：
‘(pytorch) lab@lab:~/yolov4-pytorch-master$ python get_map.py
mAP = 0.00%
Traceback (most recent call last):
  File "get_map.py", line 897, in <module>
    true_p_bar
  File "get_map.py", line 249, in draw_plot_func
    sorted_keys, sorted_values = zip(*sorted_dic_by_value)
ValueError: not enough values to unpack (expected 2, got 0)’

请问这是怎么回事0w0 感谢！

**Comment by leningyiyi** [comment]
我也遇到过这个问题，我是new_classes里面的类名字和标签文件里面不一样，改成和标签文件一样的以后对了，不知道你的是不是这样。

**Comment by bubbliiiing** [comment]
这一般不是没训练好就是哪个步骤错了，你预测的出东西吗
