### ISSUE TITLE
如何直接计算召回率和mAP

### ISSUE THREAD

**Issue by Yu-zhengbo** [bubbliiiing/yolov4-pytorch#161]
首先很感谢大神的分享，还想请教一下如何直接计算召回率和精度呢，有看到train_with_tensorboard.py可以计算mAP，想知道有没有能直接得出recall和mAP的算法吗？谢谢

**Comment by Yu-zhengbo** [comment]
遇到问题解决问题,自己已经解决啦.https://github.com/Yu-zhengbo/recall

**Comment by bubbliiiing** [comment]
recall我好像给了呀。

**Comment by Yu-zhengbo** [comment]
最近帮别人写代码又新增了ROC曲线https://github.com/Yu-zhengbo/recall-ROC-and-...      将有目标和无目标分为两类

**Comment by Yu-zhengbo** [comment]
最近帮别人写代码又新增了ROC曲线, 将有目标和无目标分为两类,顺便分享一下

**Comment by bubbliiiing** [comment]
好的噢，不过ROC中负样本你是怎么确定的兄弟。

**Comment by Yu-zhengbo** [comment]
> 好的噢，不过ROC中负样本你是怎么确定的兄弟。

我是将有检测到目标的作为正样本，没有检测到目标作为负样本，根据精度记录为得分，大神您觉得这样合理吗

**Comment by bubbliiiing** [comment]
没有检测到目标我感觉概念应该是FN，false negative。不知道作为负样本合不合适，ROC的话我主要是不清楚怎么理解TN

**Comment by ChenYll** [comment]
Traceback (most recent call last):
  File "/home/scau3090/ChenH/Python_Project/retinanet-pytorch-master/get_map.py", line 835, in <module>
    draw_plot_func(
  File "/home/scau3090/ChenH/Python_Project/retinanet-pytorch-master/get_map.py", line 235, in draw_plot_func
    sorted_keys, sorted_values = zip(*sorted_dic_by_value)
ValueError: not enough values to unpack (expected 2, got 0)

你好，你的代码写的十分规范，但是我在训练自己数据集的时候出现了这个报错，是因为数据集的问题吗还是其他原因，望解答，谢谢！

**Comment by bubbliiiing** [comment]
建议先检查一下input里面的detection-results和ground-truth
