### ISSUE TITLE
关于利用COCO工具箱计算当前数据集的0.50:0.95map问题

### ISSUE THREAD

**Issue by zhaoyixu** [bubbliiiing/yolov4-pytorch#231]
大佬，我在运行get_map.py时，将map_mode设为4，运行报错，如下：
Traceback (most recent call last):
  File "D:/code/yolov4-new-pytorch-master/get_map.py", line 113, in <module>
    get_coco_map(class_names = class_names, path = map_out_path)
  File "D:\code\yolov4-new-pytorch-master\utils\utils_map.py", line 893, in get_coco_map
    cocoDt      = cocoGt.loadRes(DR_JSON_PATH)
  File "D:\Anaconda\envs\xiaobao\lib\site-packages\pycocotools\coco.py", line 328, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range
查看了一下map_out/coco_eval文件夹下的instances_dr.json里面是空白，请问是如何解决呢？
map_mode设为1是好使的

**Comment by zhaoyixu** [comment]
只有一个类

**Comment by zhaoyixu** [comment]
instances_dr.json里面是如下这种形式：   
    {
        "image_id": 23122,
        "category_id": 1,
        "bbox": [
            271.0,
            237.0,
            372.0,
            567.0
        ],
        "score": 0.0011
    },
 {
        "image_id": 23122,
        "category_id": 1,
        "bbox": [
            -30.0,
            471.0,
            255.0,
            249.0
        ],
        "score": 0.001
    }

**Comment by bubbliiiing** [comment]
理论上，注释了这段就能跑，就是coco里面的这段

**Comment by SayHelloToEveryone** [comment]
> > 你没进行0吗
> 
> 请问下是只有voc数据集才可以使用coco工具箱计算吗，自己的数据集可以吗？ 我使用自己的数据集使用coco工具箱进行评价，即设置map_model = 4的时候，报如下错误： Traceback (most recent call last): File "/home/data/mx/yolov3/for_visDrone/visDrone_pre_inception/get_map.py", line 112, in get_coco_map(class_names = class_names, path = map_out_path) File "/home/data/mx/yolov3/for_visDrone/visDrone_pre_inception/utils/utils_map.py", line 885, in get_coco_map results_gt = preprocess_gt(GT_PATH, class_names) File "/home/data/mx/yolov3/for_visDrone/visDrone_pre_inception/utils/utils_map.py", line 820, in preprocess_gt bbox = [left, top, right - left, bottom - top, difficult, int(image_id), cls_id, (right - left) * (bottom - top) - 10.0] ValueError: invalid literal for int() with base 10: '0000291_00001_d_0000868'
将`int(image_id)`去掉int就行，因为你的image_id是string类型的

**Comment by bubbliiiing** [comment]
嗯，我给所有的库都修改一下
