### ISSUE TITLE
"model_data/CSPdarknet53_backbone_weights.pth"

### ISSUE THREAD

**Issue by hejunran** [bubbliiiing/yolov4-pytorch#264]
请问这个文件有嘛

**Comment by infochen** [comment]
百度网盘有，但是我加载这个权重会出错，但其他两个不会

> initialize network with normal type
Load weights model_data/CSPdarknet53_backbone_weights.pth.
Traceback (most recent call last):
  File "train.py", line 153, in <module>
    pretrained_dict = {k: v for k, v in pretrained_dict.items() if np.shape(model_dict[k]) == np.shape(v)}
  File "train.py", line 153, in <dictcomp>
    pretrained_dict = {k: v for k, v in pretrained_dict.items() if np.shape(model_dict[k]) == np.shape(v)}
KeyError: 'conv1.conv.weight'

**Comment by XuecWu** [comment]
@infochen  看问题是权值不匹配，看一下动backbone了没有

**Comment by infochen** [comment]
收到

**Comment by XuecWu** [comment]
@hejunran  release里面有

**Comment by hejunran** [comment]
嗯嗯
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bubbliiiing/yolov4-pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月27日(星期天) 中午11:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bubbliiiing/yolov4-pytorch] "model_data/CSPdarknet53_backbone_weights.pth" (Issue #264)





 
百度网盘有，但是我加载这个权重会出错，但其他两个不会
  
initialize network with normal type
 Load weights model_data/CSPdarknet53_backbone_weights.pth.
 Traceback (most recent call last):
 File "train.py", line 153, in 
 pretrained_dict = {k: v for k, v in pretrained_dict.items() if np.shape(model_dict[k]) == np.shape(v)}
 File "train.py", line 153, in 
 pretrained_dict = {k: v for k, v in pretrained_dict.items() if np.shape(model_dict[k]) == np.shape(v)}
 KeyError: 'conv1.conv.weight'
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bubbliiiing** [comment]
是pretrain=True调用。

**Comment by hejunran** [comment]
好的，谢谢up主




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bubbliiiing/yolov4-pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月5日(星期六) 中午1:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bubbliiiing/yolov4-pytorch] "model_data/CSPdarknet53_backbone_weights.pth" (Issue #264)





 
是pretrain=True调用。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
