### ISSUE TITLE
请问一下关于运行get_map.py报错的问题

### ISSUE THREAD

**Issue by sticktn** [bubbliiiing/yolov4-pytorch#356]
我的训练和预测都是正常的，但是在评估的时候运行**get_map.py**时报错：
~~~
Load model done.
Get predict result.
100%|██████████| 4952/4952 [01:03<00:00, 77.65it/s]
Get predict result done.
Get ground truth result.
100%|██████████| 4952/4952 [00:00<00:00, 25501.83it/s]
Get ground truth result done.
Get map.
94.76% = aeroplane AP 	||	score_threhold=0.5 : F1=0.92 ; Recall=88.07% ; Precision=96.17%
Traceback (most recent call last):
  File "/opt/yolov4/yolov4-pytorch/get_map.py", line 132, in <module>
    get_map(MINOVERLAP, True, score_threhold = score_threhold, path = map_out_path)
  File "/opt/yolov4/yolov4-pytorch/utils/utils_map.py", line 609, in get_map
    fig.canvas.set_window_title('AP ' + class_name)
AttributeError: 'FigureCanvasTkAgg' object has no attribute 'set_window_title'
~~~
不知道是什么原因

**Comment by MingAze** [comment]
ZjZkJ送 Q 币IdMaFhttp://service.qq.com/ptLogin.shtml?url=http://lai2z.spaces.live.com/w4M2P

**Comment by bubbliiiing** [comment]
鹅，是因为不同的系统导致的，你可能是debian

**Comment by MingAze** [comment]
ZjZkJ送 Q 币IdMaFhttp://service.qq.com/ptLogin.shtml?url=http://lai2z.spaces.live.com/w4M2P

**Comment by sticktn** [comment]
但我是用的ubuntu22.04出现这个问题的，pytorch版本是1.13

**Comment by bubbliiiing** [comment]
你能换个plt的版本么？
