### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by EddieEduardo** [bubbliiiing/yolov4-pytorch#42]
你好博主，非常感谢分享。
我在按照提示的步骤进行训练时出现了如下的错误：
**1 .** Traceback (most recent call last):
  File "yolov4-pytorch-master\nets\yolo4.py", line 129, in forward
    P4 = torch.cat([P4,P5_upsample],axis=1)
**_TypeError: cat() got an unexpected keyword argument 'axis'_** (已将axis改成dim，请问这个是版本原因还是？)

**2.** Traceback (most recent call last):
  File "yolov4-pytorch-master\nets\yolo_training.py", line 167, in forward
    ciou = (1 - box_ciou( pred_boxes_for_ciou[mask.bool()], t_box[mask.bool()]))* box_loss_scale[mask.bool()]
**_AttributeError: 'Tensor' object has no attribute 'bool'_**（请问这个问题怎么进行修改呢？）

**Comment by CallHoganZhang** [comment]
1.应该是版本问题，将P4 = torch.cat([P4,P5_upsample],axis=1) 改为 P4 = torch.cat([P4,P5_upsample],1  应该可以解决)
2.   首先定义一个equla_flag = torch.Tensor(0).cuda() ，然后再 ciou = (1 - box_ciou( pred_boxes_for_ciou[torch.equal(mask,equla_flag)]，这个估计是版本问题，tensor中没有bool这个属性了。

不知道上述解决方法是否存在bug，如果有，请告知，谢谢！

**Comment by EddieEduardo** [comment]
你好博主，非常感谢解答，问题已按照上述语句解决，即添加了：
_**equla_flag = torch.Tensor(0).cuda() 
ciou = (1 - box_ciou( pred_boxes_for_ciou[torch.equal(mask,equla_flag)], 
             t_box[torch.equal(mask,equla_flag)]))*box_loss_scale[torch.equal(mask,equla_flag)]**_

同时还有**2**处：
**1.** ”nets\yolo_training.py", line 79, in box_ciou
center_distance = torch.sum(torch.pow((b1_xy - b2_xy), 2), axis=-1) #需要将axis去掉
**2.** “\nets\yolo_training.py", line 86, in box_ciou
enclose_diagonal = torch.sum(torch.pow(enclose_wh,2), axis=-1) #需要将axis去掉
请问博主，直接去掉会影响原代码意义吗？

**Comment by bubbliiiing** [comment]
这应该是版本问题吧，我忘了是高还是低的情况下是dim

**Comment by scau-gqw1993** [comment]
> 
> 
> 1.应该是版本问题，将P4 = torch.cat([P4,P5_upsample],axis=1) 改为 P4 = torch.cat([P4,P5_upsample],1 应该可以解决)
> 2. 首先定义一个equla_flag = torch.Tensor(0).cuda() ，然后再 ciou = (1 - box_ciou( pred_boxes_for_ciou[torch.equal(mask,equla_flag)]，这个估计是版本问题，tensor中没有bool这个属性了。
> 
> 不知道上述解决方法是否存在bug，如果有，请告知，谢谢！

equal_flag = torch.Tensor(0).cuda()会不会写错了？我查了PyTorch文档，https://pytorch.org/docs/stable/tensors.html，self.bool() is equivalent to self.to(torch.bool)，改成mask.to(torch.bool)会不会更合适？

**Comment by scau-gqw1993** [comment]
> 
> 
> 你好博主，非常感谢解答，问题已按照上述语句解决，即添加了：
> _**equla_flag = torch.Tensor(0).cuda() ciou = (1 - box_ciou( pred_boxes_for_ciou[torch.equal(mask,equla_flag)], t_box[torch.equal(mask,equla_flag)]))*box_loss_scale[torch.equal(mask,equla_flag)]**_
> 
> 同时还有**2**处：
> **1.** ”nets\yolo_training.py", line 79, in box_ciou
> center_distance = torch.sum(torch.pow((b1_xy - b2_xy), 2), axis=-1) #需要将axis去掉
> **2.** “\nets\yolo_training.py", line 86, in box_ciou
> enclose_diagonal = torch.sum(torch.pow(enclose_wh,2), axis=-1) #需要将axis去掉
> 请问博主，直接去掉会影响原代码意义吗？

equla_flag写错了吧，应该得是1，否则的话loss_loc不会被启用。
