### ISSUE TITLE
train时，遇到invalid load key, '\x00'，怎么解决？谢谢大佬们

### ISSUE THREAD

**Issue by liupenglei** [bubbliiiing/yolov4-pytorch#44]
Loading weights into state dict...
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    pretrained_dict = torch.load(model_path, map_location=device)
  File "/home/liupenglei/anaconda3/envs/pythorch/lib/python3.6/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/liupenglei/anaconda3/envs/pythorch/lib/python3.6/site-packages/torch/serialization.py", line 564, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x00'.

**Comment by liupenglei** [comment]
好像是torch.load的问题，我的pytorch版本是1.1的，是不是必须要求1.2？

**Comment by bubbliiiing** [comment]
这个看起来像是load的是中文？

**Comment by liupenglei** [comment]
> 这个看起来像是load的是中文？

 model_path = "model_data/yolo4_weights.pth"
    # 加快模型训练的效率
    print('Loading weights into state dict...')
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model_dict = model.state_dict()
    pretrained_dict = torch.load(model_path, map_location=device)
  
就是最后一行，我不知道哪里出错了

**Comment by bubbliiiing** [comment]
可能是版本问题，一般torch.load不会出错，你重装试试看

**Comment by liupenglei** [comment]
> 可能是版本问题，一般torch.load不会出错，你重装试试看

问题解决了，，，我也不知道咋解决的。。。哈哈哈哈，现在又出来一个问题：

TypeError: cat() got an unexpected keyword argument 'axis'

源代码是：P4 = torch.cat([P4,P5_upsample],axis=1)

**Comment by liupenglei** [comment]
> > 可能是版本问题，一般torch.load不会出错，你重装试试看
> 
> 问题解决了，，，我也不知道咋解决的。。。哈哈哈哈，现在又出来一个问题：
> 
> TypeError: cat() got an unexpected keyword argument 'axis'
> 
> 源代码是：P4 = torch.cat([P4,P5_upsample],axis=1)

问题都解决了，必须得用pytorch1.2或者以上版本

**Comment by lilangyi** [comment]
> > > 可能是版本问题，一般torch.load不会出错，你重装试试看
> > 
> > 
> > 问题解决了，，，我也不知道咋解决的。。。哈哈哈哈，现在又出来一个问题：
> > TypeError: cat() got an unexpected keyword argument 'axis'
> > 源代码是：P4 = torch.cat([P4,P5_upsample],axis=1)
> 
> 问题都解决了，必须得用pytorch1.2或者以上版本

大佬，我用了pytorch1.6，还是会报错_pickle.UnpicklingError: invalid load key, '\x00'.，，不当时是怎么解决的？

**Comment by bubbliiiing** [comment]
真是玄学啊……我也不明白了

**Comment by jelly-Amy** [comment]
> 
> 
> > > > 可能是版本问题，一般torch.load不会出错，你重装试试看
> > > 
> > > 
> > > 问题解决了，，，我也不知道咋解决的。。。哈哈哈哈，现在又出来一个问题：
> > > TypeError: cat() got an unexpected keyword argument 'axis'
> > > 源代码是：P4 = torch.cat([P4,P5_upsample],axis=1)
> > 
> > 
> > 问题都解决了，必须得用pytorch1.2或者以上版本
> 
> 大佬，我用了pytorch1.6，还是会报错_pickle.UnpicklingError: invalid load key, '\x00'.，，不当时是怎么解决的？

我是1.8是pytorch也遇到了这个问题，请问你是怎么解决的？
