### ISSUE TITLE
大佬，单通道的图，跑完报错，请问怎么修改啊？

### ISSUE THREAD

**Issue by YuWang-CV** [bubbliiiing/yolov4-pytorch#51]
Input image filename:img/1.jpg
(1, 4)
b'Malignant 0.76'
Traceback (most recent call last):
  File "E:/myPython/yolov4-pytorch-master/predict.py", line 17, in <module>
    r_image = yolo.detect_image(image)
  File "E:\myPython\yolov4-pytorch-master\yolo.py", line 175, in detect_image
    outline=self.colors[self.class_names.index(predicted_class)])
  File "C:\Users\admin\Anaconda3\lib\site-packages\PIL\ImageDraw.py", line 247, in rectangle
    ink, fill = self._getink(outline, fill)
  File "C:\Users\admin\Anaconda3\lib\site-packages\PIL\ImageDraw.py", line 114, in _getink
    ink = self.draw.draw_ink(ink)
TypeError: function takes exactly 1 argument (3 given)

**Comment by bubbliiiing** [comment]
不是有一个问题汇总嘛里面有建议

**Comment by YuWang-CV** [comment]
好的，谢谢，我看看！

**Comment by YuWang-CV** [comment]
不过我选择了把单通道转成三通道做了

**Comment by bubbliiiing** [comment]
我也是这么建议的……convert一下就行了

**Comment by YuWang-CV** [comment]
嗯呢，谢谢大佬！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bubbliiiing"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 中午11:14
收件人: "bubbliiiing/yolov4-pytorch"<yolov4-pytorch@noreply.github.com&gt;; 
抄送: "奋斗纪"<731823628@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [bubbliiiing/yolov4-pytorch] 大佬，单通道的图，跑完报错，请问怎么修改啊？ (#51)





 
我也是这么建议的……convert一下就行了
