### ISSUE TITLE
size mismatch when using predict.py

### ISSUE THREAD

**Issue by charliewang789** [bubbliiiing/yolov4-pytorch#57]
hi,

when i run predict.py, when it loads model, it give error - size mismatch, any idea what's wrong?

F:\AI\classification\yolov4-pytorch>predict.py
Loading weights into state dict...
Traceback (most recent call last):
  File "F:\AI\classification\yolov4-pytorch\predict.py", line 7, in <module>
    yolo = YOLO()
  File "F:\AI\classification\yolov4-pytorch\yolo.py", line 45, in __init__
    self.generate()
  File "F:\AI\classification\yolov4-pytorch\yolo.py", line 77, in generate
    self.net.load_state_dict(state_dict)
  File "C:\Users\Charlie\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for YoloBody:
        size mismatch for yolo_head3.1.weight: copying a param with shape torch.Size([1071, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([153, 256, 1, 1]).
        size mismatch for yolo_head3.1.bias: copying a param with shape torch.Size([1071]) from checkpoint, the shape in current model is torch.Size([153]).
        size mismatch for yolo_head2.1.weight: copying a param with shape torch.Size([1071, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([153, 512, 1, 1]).
        size mismatch for yolo_head2.1.bias: copying a param with shape torch.Size([1071]) from checkpoint, the shape in current model is torch.Size([153]).
        size mismatch for yolo_head1.1.weight: copying a param with shape torch.Size([1071, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([153, 1024, 1, 1]).
        size mismatch for yolo_head1.1.bias: copying a param with shape torch.Size([1071]) from checkpoint, the shape in current model is torch.Size([153]).

**Comment by bubbliiiing** [comment]
you need to change classes_path and model_path，make them correspond to the same model

**Comment by NirFish** [comment]
> you need to change classes_path and model_path，make them correspond to the same model

I have the same problem when I use predict.py after changing  classes_path and model_path 
![image](https://user-images.githubusercontent.com/46220059/90844559-c05ad800-e396-11ea-9e14-eccc29ee6823.png)
if there are other places to change....?

ps:my english is very poor, I apologize if I use words impolitely

**Comment by bubbliiiing** [comment]
> > 您需要更改classes_path和model_path，使它们对应于同一模型
> 
> 如果还有其他地方需要更改，在更改classes_path和model_path之后使用predict.py时，我也会遇到同样的问题。
> ![图片](https://user-images.githubusercontent.com/46220059/90844559-c05ad800-e396-11ea-9e14-eccc29ee6823.png)
> 
> ps：我的英语很差，如果我不礼貌地使用单词，我表示歉意

在训练的时候也需要修改对应的txt

**Comment by hellogithubsir** [comment]
你好，我直接使用您提供的与训练模型测试时，我也碰到了相同的问题。在使用您的yolov3时没有问题。能详细的说一下嘛？
