### ISSUE TITLE
您好，请问一下您，我训练了自己的数据集，为什么跑预测的时候报错呢？这个错误怎么解决呢？麻烦您了

### ISSUE THREAD

**Issue by M15227831622** [bubbliiiing/yolov4-pytorch#71]
F:\yolov4\yolov4-pytorch-bubb>python predict.py
Loading weights into state dict...
Traceback (most recent call last):
  File "predict.py", line 7, in <module>
    yolo = YOLO()
  File "F:\yolov4\yolov4-pytorch-bubb\yolo.py", line 44, in __init__
    self.generate()
  File "F:\yolov4\yolov4-pytorch-bubb\yolo.py", line 76, in generate
    self.net.load_state_dict(state_dict)
  File "D:\anaconda3\anaconda\lib\site-packages\torch\nn\modules\module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for YoloBody:
        size mismatch for yolo_head3.1.weight: copying a param with shape torch.Size([75, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([21, 256, 1, 1]).
        size mismatch for yolo_head3.1.bias: copying a param with shape torch.Size([75]) from checkpoint, the shape in current model is torch.Size([21]).
        size mismatch for yolo_head2.1.weight: copying a param with shape torch.Size([75, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([21, 512, 1, 1]).
        size mismatch for yolo_head2.1.bias: copying a param with shape torch.Size([75]) from checkpoint, the shape in current model is torch.Size([21]).
        size mismatch for yolo_head1.1.weight: copying a param with shape torch.Size([75, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([21, 1024, 1, 1]).
        size mismatch for yolo_head1.1.bias: copying a param with shape torch.Size([75]) from checkpoint, the shape in current model is torch.Size([21]).

请大佬们帮忙看一下，我要怎么改才能呢？谢谢！

**Comment by M15227831622** [comment]
![image](https://user-images.githubusercontent.com/53086000/92189681-dafe7800-ee91-11ea-9cf2-abf465a3e2a4.png)
  这个图片里面  model_path="model_data/epoch......."训练完之后有很多个epoch.....pth。我应该选用哪一个呢？

**Comment by bubbliiiing** [comment]
随便选一个，train.py yolo.py两个txt都需要修改

**Comment by M15227831622** [comment]
好的，谢谢您

**Comment by M15227831622** [comment]
> 随便选一个，train.py yolo.py两个txt都需要修改

好的，谢谢您指导
